export const unrealLodBones = [
  // left hand UE5
  "hand_l",
  "thumb_01_l",
  "thumb_02_l",
  "thumb_03_l",
  "thumb_03_l_end",
  "index_metacarpal_l",
  "index_01_l",
  "index_02_l",
  "index_03_l",
  "index_03_l_end",
  "middle_metacarpal_l",
  "middle_01_l",
  "middle_02_l",
  "middle_03_l",
  "middle_03_l_end",
  "ring_metacarpal_l",
  "ring_01_l",
  "ring_02_l",
  "ring_03_l",
  "ring_03_l_end",
  "pinky_metacarpal_l",
  "pinky_01_l",
  "pinky_02_l",
  "pinky_03_l",
  "pinky_03_l_end",

  // right hand UE5
  "hand_r",
  "thumb_01_r",
  "thumb_02_r",
  "thumb_03_r",
  "thumb_03_r_end",
  "index_metacarpal_r",
  "index_01_r",
  "index_02_r",
  "index_03_r",
  "index_03_r_end",
  "middle_metacarpal_r",
  "middle_01_r",
  "middle_02_r",
  "middle_03_r",
  "middle_03_r_end",
  "ring_metacarpal_r",
  "ring_01_r",
  "ring_02_r",
  "ring_03_r",
  "ring_03_r_end",
  "pinky_metacarpal_r",
  "pinky_01_r",
  "pinky_02_r",
  "pinky_03_r",
  "pinky_03_r_end",

  // foot parts (TODO: check if needed. I have no clue what these bones are)
  "ball_l",
  "ball_l_end",
  "ball_r",
  "ball_r_end",

  // IDK what these are TBH
  "lowerarm_twist_01_l",
  "lowerarm_twist_01_l_end",
  "lowerarm_twist_02_l",
  "lowerarm_twist_02_l_end",
  "lowerarm_twist_01_r",
  "lowerarm_twist_01_r_end",
  "lowerarm_twist_02_r",
  "lowerarm_twist_02_r_end",
  "upperarm_twist_01_l",
  "upperarm_twist_01_l_end",
  "upperarm_twist_02_l",
  "upperarm_twist_02_l_end",
  "upperarm_twist_01_r",
  "upperarm_twist_01_r_end",
  "upperarm_twist_02_r",
  "upperarm_twist_02_r_end",
  "thigh_twist_01_l",
  "thigh_twist_01_l_end",
  "thigh_twist_02_l",
  "thigh_twist_02_l_end",
  "thigh_twist_01_r",
  "thigh_twist_01_r_end",
  "thigh_twist_02_r",
  "thigh_twist_02_r_end",
  "calf_twist_01_l",
  "calf_twist_01_l_end",
  "calf_twist_02_l",
  "calf_twist_02_l_end",
  "calf_twist_01_r",
  "calf_twist_01_r_end",
  "calf_twist_02_r",
  "calf_twist_02_r_end",

  // IK prob not needed
  "ik_foot_root",
  "ik_foot_l",
  "ik_foot_l_end",
  "ik_foot_r",
  "ik_foot_r_end",
  "ik_hand_root",
  "ik_hand_gun",
  "ik_hand_l",
  "ik_hand_l_end",
  "ik_hand_r",
  "ik_hand_r_end",

  // ??????
  "interaction",
  "interaction_end",
  "center_of_mass",
  "center_of_mass_end",
];
