import crypto from "crypto";

import type {
  CharacterDescription,
  UserData,
  UserIdentityUpdate,
} from "@mml-io/3d-web-user-networking";
import express from "express";

export type AuthUser = {
  // connectionId is the connection identifier for the user - it is null before the client websocket is connected
  connectionId: number | null;
  // userData is the user's presentation in the world (username and character description)
  userData?: UserData;
  // sessionToken is the token that is generated by this authenticator and the user uses to authenticate their websocket connection
  sessionToken: string;
};

export type BasicUserAuthenticatorOptions = {
  devAllowUnrecognizedSessions: boolean;
};

const defaultOptions: BasicUserAuthenticatorOptions = {
  devAllowUnrecognizedSessions: false,
};

export class BasicUserAuthenticator {
  private usersByConnectionId = new Map<number, AuthUser>();
  private userBySessionToken = new Map<string, AuthUser>();

  constructor(
    private characterDescriptions: CharacterDescription[],
    private options: BasicUserAuthenticatorOptions = defaultOptions,
  ) {}

  private randomCharacterDescription(): CharacterDescription {
    return this.characterDescriptions[
      Math.floor(Math.random() * this.characterDescriptions.length)
    ];
  }

  public async generateAuthorizedSessionToken(req: express.Request): Promise<string> {
    const sessionToken = crypto.randomBytes(20).toString("hex");
    const authUser: AuthUser = {
      connectionId: null,
      sessionToken,
    };

    this.userBySessionToken.set(sessionToken, authUser);
    return sessionToken;
  }

  public async onClientConnect(
    connectionId: number,
    sessionToken: string,
    userIdentityPresentedOnConnection?: UserData,
  ): Promise<UserData | true | Error> {
    console.log(`Connection ID: ${connectionId} joined with token`);
    let user = this.userBySessionToken.get(sessionToken);
    if (!user && this.options.devAllowUnrecognizedSessions) {
      console.warn(`Dev mode: allowing unrecognized session token`);
      user = {
        connectionId: null,
        sessionToken,
      };
      this.userBySessionToken.set(sessionToken, user);
    }

    if (!user) {
      console.error(
        `Invalid initial user-update for connectionId ${connectionId}, unknown session`,
      );
      return new Error(
        `Invalid initial user-update for connectionId ${connectionId}, unknown session`,
      );
    }

    if (user.connectionId !== null) {
      console.error(`Session token already connected`);
      return new Error(`Session token already connected`);
    }

    user.connectionId = connectionId;
    user.userData = {
      userId: crypto.randomUUID(),
      username: userIdentityPresentedOnConnection?.username
        ? userIdentityPresentedOnConnection.username
            .replace(/[\x00-\x1f\x7f]/g, "")
            .slice(0, 256)
        : `User ${connectionId}`,
      characterDescription:
        userIdentityPresentedOnConnection?.characterDescription ??
        this.randomCharacterDescription(),
      colors: userIdentityPresentedOnConnection?.colors ?? null,
    };
    console.log(`Connection ID: ${connectionId} connected with user data`, user.userData);
    this.usersByConnectionId.set(connectionId, user);
    return user.userData;
  }

  public getClientIdForSessionToken(sessionToken: string): { id: number } | null {
    const user = this.userBySessionToken.get(sessionToken);
    if (!user) {
      console.error("getClientIdForSessionToken - unknown session");
      return null;
    }
    if (user.connectionId === null) {
      console.error("getClientIdForSessionToken - client not connected");
      return null;
    }
    return { id: user.connectionId };
  }

  public onClientUserIdentityUpdate(
    connectionId: number,
    msg: UserIdentityUpdate,
  ): UserIdentityUpdate | true | Error {
    const user = this.usersByConnectionId.get(connectionId);

    if (!user) {
      console.error(`onClientUserIdentityUpdate - unknown connectionId ${connectionId}`);
      return new Error(`onClientUserIdentityUpdate - unknown connectionId ${connectionId}`);
    }

    if (!user.userData) {
      console.error(`onClientUserIdentityUpdate - no user data for connectionId ${connectionId}`);
      return new Error(
        `onClientUserIdentityUpdate - no user data for connectionId ${connectionId}`,
      );
    }

    const update: UserIdentityUpdate = {
      username: msg.username
        ? msg.username.replace(/[\x00-\x1f\x7f]/g, "").slice(0, 256)
        : user.userData.username,
      characterDescription: msg.characterDescription ?? user.userData.characterDescription,
      colors: msg.colors ?? user.userData.colors,
    };

    user.userData = {
      userId: user.userData.userId,
      username: update.username,
      characterDescription: update.characterDescription,
      colors: update.colors,
    };

    return update;
  }

  public getSessionAuthToken(_sessionToken: string): string | null {
    return null;
  }

  public onClientDisconnect(connectionId: number) {
    console.log(`Remove user-session for ${connectionId}`);
    const userData = this.usersByConnectionId.get(connectionId);
    if (userData) {
      this.userBySessionToken.delete(userData.sessionToken);
      this.usersByConnectionId.delete(connectionId);
    }
  }

  public dispose(): void {
    this.usersByConnectionId.clear();
    this.userBySessionToken.clear();
  }
}
