import fs from "fs";
import path from "path";
import url from "url";

import {
  Networked3dWebExperienceServer,
  Networked3dWebExperienceServerConfig,
} from "@mml-io/3d-web-experience-server";
import type { CharacterDescription } from "@mml-io/3d-web-user-networking";
import express from "express";

import { BasicUserAuthenticator } from "./BasicUserAuthenticator";

const dirname = url.fileURLToPath(new URL(".", import.meta.url));

const PORT = process.env.PORT || 8080;

const defaultAvatars: CharacterDescription[] = [
  { meshFileUrl: "/assets/models/avatar-1-bodyA-skin01.glb" },
  { meshFileUrl: "/assets/models/avatar-2-bodyB-skin03.glb" },
  { meshFileUrl: "/assets/models/avatar-3-bodyA-skin05.glb" },
  { meshFileUrl: "/assets/models/avatar-4-bodyB-skin07.glb" },
];

const userAuthenticator = new BasicUserAuthenticator(defaultAvatars, {
  /*
   This option allows sessions that are reconnecting from a previous run of the server to connect even if the present a
   session token that was not generated by this run of the server.

   This is useful for development, but in deployed usage, it is recommended to set this to false.
  */
  devAllowUnrecognizedSessions: true,
});

const webClientBuildDir = path.join(dirname, "../../client/build/");
const indexContent = fs.readFileSync(path.join(webClientBuildDir, "index.html"), "utf8");
const mmlDocumentsDirectoryRoot = path.resolve(dirname, "../mml-documents");
const mmlDocumentsWatchPath = "**/*.html";

const app = express();
app.enable("trust proxy");

const networked3dWebExperienceServer = new Networked3dWebExperienceServer({
  networkPath: "/network",
  userAuthenticator,
  mmlServing: {
    documentsWatchPath: mmlDocumentsWatchPath,
    documentsDirectoryRoot: mmlDocumentsDirectoryRoot,
    documentsUrl: "/mml-documents/",
  },
  webClientServing: {
    indexUrl: "/",
    indexContent,
    clientBuildDir: webClientBuildDir,
    clientUrl: "/web-client/",
    clientWatchWebsocketPath:
      process.env.NODE_ENV !== "production" ? "/web-client-build" : undefined,
  },
  assetServing: {
    assetsDir: path.resolve(dirname, "../../../assets/"),
    assetsUrl: "/assets/",
  },
  worldConfig: {
    mmlDocuments: { example: { url: `ws:///mml-documents/example-mml.html` } },
    environmentConfiguration: {
      fog: {
        fogFar: 0,
      },
    },
    avatarConfiguration: {
      allowCustomAvatars: true,
      availableAvatars: defaultAvatars.map((desc, i) => ({
        name: `Avatar ${i + 1}`,
        meshFileUrl: desc.meshFileUrl!,
      })),
    },
    spawnConfiguration: {
      enableRespawnButton: true,
    },
    allowOrbitalCamera: true,
    enableChat: true,
  },
} satisfies Networked3dWebExperienceServerConfig);
networked3dWebExperienceServer.registerExpressRoutes(app);

// Start listening
console.log("Listening on port", PORT);
app.listen(PORT);
